"""Fiches explicatives (rédaction maison) pour les annonces majeures.

Chaque fiche : (motif regex sur le titre anglais, ce que ça mesure, effet habituel, pourquoi c'est suivi).
Dans « effet », {cur} est remplacé par la devise (USD, EUR…). Le premier motif qui correspond gagne.
"""

import re

FICHES = [
    (r"core pce",
     "L'évolution des prix des dépenses des ménages, hors énergie et alimentation.",
     "Plus haut que prévu → plutôt positif pour le {cur} (la Fed reste ferme sur les taux).",
     "C'est la mesure d'inflation préférée de la Fed pour décider de ses taux."),
    (r"\bpce\b",
     "L'évolution des prix de tout ce que consomment les ménages.",
     "Plus haut que prévu → plutôt positif pour le {cur}.",
     "Complète le Core PCE ; la Fed le surveille de près."),
    (r"core cpi",
     "L'inflation des prix à la consommation, hors énergie et alimentation (plus stable).",
     "Plus haut que prévu → positif pour le {cur} (taux élevés plus longtemps).",
     "L'une des annonces qui fait le plus bouger les marchés : elle oriente directement la banque centrale."),
    (r"\bcpi\b|\bhicp\b|consumer price",
     "L'évolution des prix payés par les consommateurs : c'est l'inflation.",
     "Plus haut que prévu → positif pour le {cur} (la banque centrale peut garder des taux élevés).",
     "L'inflation est l'objectif n°1 des banques centrales : chaque surprise change les anticipations de taux."),
    (r"\bppi\b|producer price",
     "L'évolution des prix de vente des producteurs.",
     "Plus haut que prévu → plutôt positif pour le {cur}.",
     "Signal avancé : la hausse des coûts des entreprises finit souvent dans les prix aux consommateurs."),
    (r"adp",
     "Les créations d'emplois dans le secteur privé, selon le cabinet ADP.",
     "Plus haut que prévu → positif pour le {cur}.",
     "Donne un avant-goût du rapport officiel sur l'emploi (NFP), publié deux jours plus tard."),
    (r"non-?farm (employment|payrolls)|\bnfp\b",
     "Le nombre d'emplois créés le mois dernier aux États-Unis, hors agriculture.",
     "Plus haut que prévu → positif pour le {cur}.",
     "L'annonce la plus attendue du mois : elle provoque souvent les plus gros mouvements de l'année."),
    (r"unemployment claims|jobless claims",
     "Le nombre de nouvelles inscriptions au chômage sur la semaine.",
     "Plus BAS que prévu → positif pour le {cur} (moins de chômeurs = économie solide).",
     "Donnée hebdomadaire : c'est la mesure la plus rapide de la santé du marché de l'emploi."),
    (r"unemployment rate",
     "La part de la population active sans emploi.",
     "Plus BAS que prévu → positif pour le {cur}.",
     "Un chômage bas soutient la consommation et laisse la banque centrale plus libre de monter les taux."),
    (r"unemployment change|claimant count",
     "La variation du nombre de demandeurs d'emploi sur le mois.",
     "Plus BAS que prévu → positif pour le {cur}.",
     "Indique si le marché du travail se renforce ou se dégrade."),
    (r"average hourly earnings|wage",
     "L'évolution des salaires.",
     "Plus haut que prévu → positif pour le {cur}.",
     "Des salaires qui montent vite alimentent l'inflation, donc les décisions de taux."),
    (r"jolts|job openings",
     "Le nombre de postes à pourvoir dans les entreprises.",
     "Plus haut que prévu → positif pour le {cur}.",
     "Mesure la demande de travail : beaucoup d'offres = économie tendue."),
    (r"gdp price index",
     "L'inflation mesurée sur l'ensemble de la production du pays.",
     "Plus haut que prévu → plutôt positif pour le {cur}.",
     "Complète le PIB en montrant la part de la croissance due à la hausse des prix."),
    (r"\bgdp\b",
     "La croissance de l'économie : la valeur de tout ce qui est produit dans le pays.",
     "Plus haut que prévu → positif pour le {cur}.",
     "C'est la mesure la plus large de la santé d'une économie. Les versions « finales » bougent moins le marché que la première estimation."),
    (r"ism manufacturing|manufacturing pmi|chicago pmi",
     "Un sondage auprès des directeurs d'achat de l'industrie. Au-dessus de 50 = l'activité progresse, en dessous = elle recule.",
     "Plus haut que prévu → positif pour le {cur}.",
     "Indicateur avancé : les acheteurs voient avant tout le monde si les commandes accélèrent ou ralentissent."),
    (r"ism services|services pmi|non-manufacturing",
     "Un sondage auprès des directeurs d'achat des services. Au-dessus de 50 = expansion.",
     "Plus haut que prévu → positif pour le {cur}.",
     "Les services représentent la majorité de l'économie des pays développés."),
    (r"composite pmi",
     "L'activité globale (industrie + services). Au-dessus de 50 = expansion.",
     "Plus haut que prévu → positif pour le {cur}.",
     "Résume en un chiffre la dynamique de l'économie."),
    (r"retail sales",
     "L'évolution des ventes des commerces.",
     "Plus haut que prévu → positif pour le {cur}.",
     "La consommation est le premier moteur de la croissance."),
    (r"consumer confidence|consumer sentiment",
     "Le moral des ménages, mesuré par sondage.",
     "Plus haut que prévu → positif pour le {cur}.",
     "Des ménages confiants dépensent davantage."),
    (r"crude oil inventories",
     "La variation des stocks de pétrole brut aux États-Unis sur la semaine.",
     "Stocks plus BAS que prévu → positif pour le prix du pétrole (et le CAD).",
     "Fait bouger le pétrole chaque mercredi ; impact surtout sur le brut et les devises liées."),
    (r"durable goods",
     "Les commandes de biens durables (machines, véhicules, équipements…).",
     "Plus haut que prévu → positif pour le {cur}.",
     "Reflète l'envie d'investir des entreprises."),
    (r"fomc (statement|meeting)|federal funds rate|interest rate decision|rate decision|official bank rate|main refinancing|cash rate",
     "La décision de la banque centrale sur son taux directeur.",
     "Hausse ou ton ferme (« hawkish ») → positif pour le {cur} ; baisse ou ton souple (« dovish ») → négatif.",
     "L'événement le plus important pour une devise : il fixe le coût de l'argent."),
    (r"minutes",
     "Le compte rendu détaillé de la dernière réunion de politique monétaire.",
     "Ton plus ferme que prévu → positif pour le {cur}.",
     "Révèle les débats internes et donne des indices sur les prochaines décisions."),
    (r"press conference",
     "La conférence de presse qui suit la décision de taux.",
     "Ton ferme → positif pour le {cur} ; ton souple → négatif.",
     "Les réponses aux journalistes font souvent plus bouger le marché que la décision elle-même."),
    (r"powell|lagarde|bailey|ueda|schlegel",
     "Une prise de parole du président ou de la présidente de la banque centrale.",
     "Ton ferme (inflation, taux élevés) → positif pour le {cur} ; ton souple → négatif.",
     "Chaque mot est analysé pour deviner les prochaines décisions de taux."),
    (r"speaks|testifies",
     "Une prise de parole publique d'un responsable.",
     "Ton ferme → positif pour le {cur} ; ton souple → négatif.",
     "Peut faire bouger le marché si le discours donne des indices sur la politique à venir."),
]


def fiche(e):
    t = e["title"].lower()
    for pattern, mesure, effet, pourquoi in FICHES:
        if re.search(pattern, t):
            return mesure, effet.format(cur=e["cur"]), pourquoi
    return None
